### ISSUE TITLE
定义两个菜单同时被选中了

### ISSUE THREAD

**Issue by hanchenglong001** [amisadmin/fastapi-amis-admin#103]
![image](https://github.com/amisadmin/fastapi-amis-admin/assets/56539098/afced7ad-1ef6-4b8f-b6c8-84110197ae51)
![image](https://github.com/amisadmin/fastapi-amis-admin/assets/56539098/6339df1d-e97b-4f5f-991c-1f27447ecb28)

**Comment by amisadmin** [comment]
使用不同的src
