### ISSUE TITLE
如果我只想用它在我自己的项目中生成 crud api 不想要界面怎么做？

### ISSUE THREAD

**Issue by EchoShoot** [amisadmin/fastapi-amis-admin#107]
我写了一个自己的项目有自己的管理界面，不过很喜欢 crud api 生成方式，实在是优雅！如果我只需要crud这块生成api应该怎么做？

**Comment by amisadmin** [comment]
继承Crud类, 单独创建Crud实例就行.但是Admin类功能更多,并且不会有额外的开销.
