### ISSUE TITLE
在新建数据的时候面临的字段问题

### ISSUE THREAD

**Issue by EchoShoot** [amisadmin/fastapi-amis-admin#111]
在使用 admin.ModelAdmin 配置 model 后可以很方便的拥有增删改查的能力，但新增的时候如果遇到不想显示给用户的字段怎么办？
我们的表是这样的

id | url | domain
---|---|---
1 | http://www.example.com/abc | www.example.com

其中 domain 字段是需要根据 url 生成的，并且要存储在数据库中建立索引。这一个字段不需要展示给用户。
我目前是配置 amis_form_item=Hidden() 来隐藏的，但是依然会传递，不知道有没有什么更好的方案？

**Comment by amisadmin** [comment]
create_fields, create_exclude
