### ISSUE TITLE
右侧编辑图标点不动的情况

### ISSUE THREAD

**Issue by EchoShoot** [amisadmin/fastapi-amis-admin#116]
鼠标移动到某行上，右侧会有悬浮快捷按钮，存在两个问题：
1. 经常出现右侧编辑按钮点不动的情况（需要关闭服务重启后才能点动）
2. 悬浮快捷键，会遮盖最右侧的列，导致快速编辑功能没法使用。

**Comment by amisadmin** [comment]
这个问题需要baidu amis更新. fastapi-amis-admin v0.6.1支持配置`display_item_action_as_column = True`将表项动作展示为操作列.
