### ISSUE TITLE
请问搜索栏怎么设置默认值，比如下拉设置一个默认的选项

### ISSUE THREAD

**Issue by tomasky** [amisadmin/fastapi-amis-admin#124]
请问搜索栏怎么设置默认值，比如下拉设置一个默认的选项，我知道可以在get_page里面直接填充filterform对应的value
,但是还是想问下怎么直接设置

**Comment by amisadmin** [comment]
重写`get_list_table`, 给table添加`defaultParams`属性.

**Comment by tomasky** [comment]
好的，我试下，

**Comment by tomasky** [comment]
其实有了get_page 重构，这个框架灵活性完全不是问题，感谢作者这轮子，熟悉后，很高效。
