### ISSUE TITLE
Pydantic 2 support?

### ISSUE THREAD

**Issue by MatsiukMykola** [amisadmin/fastapi-amis-admin#127]
SQLModel does not support Pydantic 2
but in your sources, I saw using Pydantic 2
Do you use https://github.com/tiangolo/sqlmodel/pull/632 ?
Does your library support SQLAlchemy 2?

can explain please, I try to help to adapt, but not understand if this is needed or not.

**Comment by amisadmin** [comment]
`fastapi-amis-admin` should support SQLAlchemy 2 and Pydantic 2. 
I am also following the updates on https://github.com/tiangolo/sqlmodel/pull/632, but the main branch of Sqlmodel has not merged it yet. 
Additionally, many of my small projects depend on Sqlmodel, such as `fastapi-user-auth`, so I have been waiting for updates to Sqlmodel. 
If you can adapt it, that would be great, but I am concerned that tiangolo may have a different implementation for Sqlmodel. 
It may be necessary to enable a new branch for now and merge it when Sqlmodel officially supports the v2 version.

**Comment by MatsiukMykola** [comment]
hm... you're right, need to wait
anyway big thanks for your great library!
