### ISSUE TITLE
auth成功后app为空

### ISSUE THREAD

**Issue by lifengmds** [amisadmin/fastapi-amis-admin#141]
配置好auth成功登陆后出现404，app mount似乎不成功，左侧菜单为空。去掉auth登陆验证则没问题。
有什么要配置吗？

**Comment by ElfenSterben** [comment]
> 4，app mount似乎不成功，左侧菜单为空。去掉auth登陆验证则没问题。
> 有什么要配置吗？

兄弟，你这个咋解决的

**Comment by zinohome** [comment]
启用auth后 admin用户没有菜单权限的 ，使用root用户登录，在授权中给admin用户授权即可
