### ISSUE TITLE
如何通过点击跳转到新页面？

### ISSUE THREAD

**Issue by cic1988** [amisadmin/fastapi-amis-admin#153]
目前看到的案例里面都是页面通过register_admin 在初始化的时候已经设定好了。我在测试的时候需要通过点击某个item（比如一个列表）然后这个列表会打开或跳转到一个新页面 (比如ArticleOverviewPage)。而这个页面并没有在初始化的时候就设定好。

请问有没有实现的例子呢？多谢各位。

**Comment by Sug2077** [comment]
1. 在amis文档找到对应组件，实现方法
2. 在amis-admin查找源码实现上述方法
