### ISSUE TITLE
请问能否弄一个增加自定义组件的例子？

### ISSUE THREAD

**Issue by markqiu** [amisadmin/fastapi-amis-admin#65]

**Comment by amisadmin** [comment]
参考: fastapi_amis_admin_demo和fastapi_user_auth_demo.  
可以在定义Field时使用 amis_form_item 和amis_table_column参数

**Comment by markqiu** [comment]
感谢如此迅速的回答！！！

我发现我这个问题似乎应该在amis中提。

我想具体一点，比如我想把一个第三方的react库引入amis，应该如何做，可不可以弄个教程。
我也愿意贡献代码或者文档，但目前需要人指导一下，谢谢。

**Comment by amisadmin** [comment]
如果你愿意贡献代码或者文档，我也很乐意为你提供思路或相关解答。
目前fastapi-amis-admin是依赖百度amis jssdk，关于引入第三方组件我暂时也没有太深入了解，可能需要查看百度amis文档，结合admin生成输出的json对比。
fastapi-amis-admin支持自定义全部jssdk的组件。
1. 在定义模型时，通过Field的amis_xxx参数指定组件。
2. 在Admin类中重写amis组件映射方法，例如，get_form_item，get_form，get_table_column...，类似可重写的方法很多。你可以通过item的name识别特定字段。
3. 你可以重写amis的默认模板，amis/templates/app.html和page.html

**Comment by markqiu** [comment]
好的，我先研究研究，会把成果定期公布在这里。
有兴趣的同学也可以一起来参与一下

**Comment by swelcker** [comment]
Next version will include the Custom component. Then it will be much simpler to introduce custom components.
look here for reference: https://aisuda.bce.baidu.com/amis/zh-CN/components/custom
