### ISSUE TITLE
QuickSaveItemApi错误，请修正代码

### ISSUE THREAD

**Issue by zinohome** [amisadmin/fastapi-amis-admin#67]
admin/admin.py 文件 中 ：
            primaryField=self.pk_name,
            quickSaveItemApi=f"put:{self.router_path}/item/" + "${id}",
改为：
            primaryField=self.pk_name,
            quickSaveItemApi=f"put:{self.router_path}/item/${self.pk_name}"
否则pk_name不为id时，会报405错误

**Comment by amisadmin** [comment]
感谢反馈

**Comment by zinohome** [comment]
另外，代码中有不少地方讲Primarykey直接写成了id，还是请兼顾一下Primarykey不为id的情况，用pk_name变量统一一下吧

**Comment by amisadmin** [comment]
欢迎提交一个PR
