### ISSUE TITLE
一个好玩意，没有好说明书，这怎么整

### ISSUE THREAD

**Issue by kingmo888** [amisadmin/fastapi-amis-admin#70]
按照文档中的page添加后，做操作各种失败，
而demo中通过faa run执行的模式下，跟原教程完全不同。

这让人咋入手。

教程并没有一个从头到尾的哪怕一个简单的demo。感觉学习成本挺高的，

可能我智力有问题吧，
抱歉。

还是想多说一句，一个好东西，如果他是使用广泛的，必然搜索引擎多少都会有相关的使用片段。
可结果是，搜索引擎中检索到的所有相关内容，都是简单的复制官方不完善的文档而已。一个自定义使用的文章都不存在。

**Comment by lianghuimin110** [comment]
老哥，我敲faa总是command not found，但是看了包已经装到安装路径下，环境变量也没问题。有解吗
