### ISSUE TITLE
https://unpkg.com/的资源在国内访问速度慢,是否考虑把静态js css资源放入安装包里面呢?

### ISSUE THREAD

**Issue by zxyaust** [amisadmin/fastapi-amis-admin#86]
测试网上测试很多资源在国内2-3秒,国外几百毫秒
![image](https://user-images.githubusercontent.com/16290254/228430552-2b6dd3ed-8d2f-40a8-b956-5625b5063e30.png)
静态资源是否可以有选择性的使用呢?让用户自己配置一下,如果国内的可以选择其他资源,权做参考哈

**Comment by amisadmin** [comment]
可通过[Settings](https://docs.gh.amis.work/amis_admin/Settings/#amis_cdn)对象自定义cdn地址(支持挂载静态资源在本地).

**Comment by liunux4odoo** [comment]
我打包了一个`fastapi-amis-admin-offline`，包含了swagger/redoc/amis需要的静态资源，可以使amis_admin离线使用：
```
from fastapi_amis_admin_offline import patch_offline

...
app = FastAPI()
patch_offline(app)
```

**Comment by oubeichen** [comment]
> 我打包了一个`fastapi-amis-admin-offline`，包含了swagger/redoc/amis需要的静态资源，可以使amis_admin离线使用：
> 
> ```
> from fastapi_amis_admin_offline import patch_offline
> 
> ...
> app = FastAPI()
> patch_offline(app)
> ```

希望能更新一个版本，或者怎么生成文件的可以写成一个脚本让大家手动更新
