### ISSUE TITLE
Multiple databases support

### ISSUE THREAD

**Issue by lastochka364** [amisadmin/fastapi-amis-admin#89]
Hello. I need to connect two databases: PostgreSQL and SQlite, for interacting with each other from single admin panel.
Is it possible right now, and if yes, how it can be implemented?

**Comment by amisadmin** [comment]
You can customize the engine object under AdminApp and add middleware for the database.

```py
# 1
class  Db2AdminApp(AdminApp):
    engine: AsyncDatabase=db2
    ...

# 2
fastapi.add_middleware(BaseHTTPMiddleware, dispatch=db2.asgi_dispatch)
```
