### ISSUE TITLE
需要帮助

### ISSUE THREAD

**Issue by STM32King** [amisadmin/fastapi-amis-admin#93]
你好,大佬.
    我是前端一枚,最近在学习FastAPI,刚刚入门,amis还没有学习,打算学习一下.主要目的是想快速搭建一套前后端程序.
    这两天突然发现用fastapi写的admin很少,感觉您的[fastapi-amis-admin挺好的,但是苦于没有视频教程,我看了文档,以我目前的水平,使用这个框架文档也无法运行运行起来一个Dome,希望能得到您的指导.当然我会给您一些钱,作为您付出的补偿.
     我的手机号码13009476592(微信同步).
     期待您的回复.
     谢谢!!!

**Comment by amisadmin** [comment]
这套系统基于amis，比较适合一些常见通用的页面。如果需要自由度的页面可能不太适合，你可以先了解一下。
